version: '3.3'
services:
  db:
    image: mysql:5.7
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=CatchABall
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      
  client:
    stdin_open: true
    environment:
      - WATCHPACK_POLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '3000:3000'

  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - db
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      MYSQL_HOST_IP: db
    ports:
      - '1117:1117'

  adminer:
      image: adminer:latest
      restart: unless-stopped
      ports:
        - 8192:8192
      depends_on:
        - db
      environment:
        ADMINER_DEFAULT_SERVER: db
volumes:
  db:
    driver: local
    